# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test-app
  template:
    metadata:
      labels:
        app: devops-test-app
    spec:
      containers:
        - name: devops-test-app
          image: kaisteng/devops-test-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-test-app-service
spec:
  selector:
    app: devops-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer